my_site/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name= "blog"
urlpatterns = [
    path("" , views.Home.as_view() , name = "home"),
    path("all_posts/" ,views.Posts.as_view() ,name = "all_posts"),
    path("tag/<slug:tag_slug>/" ,views.Posts.as_view() , name="posts_by_tags"),
    path("<int:year>/<int:month>/<int:day>/<slug:slug>" , views.PostDetail.as_view(), name ="post_detail"),
    path("<int:id>/" , views.just_get_it , name = "justgetit"),
    path("<int:id>/share-post/" , views.SharePost.as_view() , name = "share_post"),

    path("feed/" , LatestPostsFeed() , name="post_feed"),
    path("search/"  , views.PostSerach.as_view(), name= "post_search")
]

#task = learn how to use the custom model manager with Class based views, and make a "all blogs" page

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include("blog.urls" , namespace="blog")),
    path("sitemap.xml", sitemap, {"sitemaps":sitemaps} , name="django.contrib.sitemaps.views.sitemap"),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

my_site/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
from django.conf import settings
# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=PostModel.Status.Published)
class PostModel(models.Model):
    objects = models.Manager()# the defaul manager
    presented = PublishedManager() # the custom manager
    tags = TaggableManager()
    class Status(models.TextChoices):
        Draft = "DF" , "Draft"
        Published = "PB" , "Published"
    title = models.CharField(max_length=300)
    content = models.TextField()
    slug = models.SlugField(max_length=250, unique_for_date="published")
    image = models.ImageField(upload_to="posts/")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE , related_name="blog_posts")
    published = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField( choices=Status, default=Status.Draft, max_length=2)
    class Meta:
        verbose_name = "post"
        ordering= ["-published"]
        
        indexes = [
            # could have just used db_index=True in the published field, but it doesn't index in decending order
            models.Index(fields=[("-published")]) 
        ]

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={
            "slug": self.slug ,"day":self.published.day 
            ,"month":self.published.month, "year": self.published.year
            })
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey( PostModel, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField( max_length=254)
    body = models.TextField(max_length=400)
    created = models.DateTimeField( auto_now_add=True)
    updated = models.DateTimeField( auto_now=True)
    active = models.BooleanField(default=True)

    class Meata:
        ordering= ["craeted"]
        indexes = [models.Index(fields=[("created")])]
    
    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

my_site/blog/forms.py
from django import forms
from .models import Comment
class EmailPostForm(forms.Form):
    name = forms.CharField( max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField( required=False , widget=forms.Textarea)

class SearchForm(forms.Form):
    query = forms.CharField()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment 
        fields = ("name", "email" , "body")

my_site/blog/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import PostModel
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST #makes a view to only be used for post requests and it will throw an http 405(mehtod not allowed) otherwise
from django.views.generic import ListView, View
from django.core.mail import send_mail
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from .forms import EmailPostForm, CommentForm, SearchForm
from taggit.models import Tag
from django.db.models import Count, Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
# Create your views here.

class Home(ListView):
    model = PostModel
    template_name = "blog/home.html"
    context_object_name= "newposts"
    queryset= PostModel.presented.all()[:3]
class Posts(ListView):
    template_name = "blog/all_posts.html"
    model = PostModel
    queryset = PostModel.presented.all()
    paginate_by = 5
    context_object_name = "posts"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        tag_slug = self.kwargs.get("tag_slug" , False)
        if tag_slug:
            context["tag"] = get_object_or_404(Tag , slug =tag_slug )
            context["posts"] = PostModel.presented.filter(tags__in=[context["tag"]])
        return context
    

    
"""   
def Posts(request):
    post_lists = PostModel.published.all()
    paginator = Paginator(post_lists , 5)
    page_number = request.GET.get("page" , 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    return render(request , "all_posts.html" , {"posts": posts })
"""
class PostDetail(View):
    def get(self , request, slug , day,year,month):
        form = CommentForm()
        selected_post = get_object_or_404(
            PostModel ,status= PostModel.Status.Published, slug = slug, published__day=day
            ,published__month = month , published__year=year
            )
        #similar posts based on the tags
        post_tags = selected_post.tags.values_list("id",flat=True)
        similar_posts = PostModel.presented.filter(tags__in=post_tags).exclude(id = selected_post.id)
        similar_posts = similar_posts.annotate(same_tags = Count("tags" , filter=Q(tags__in=post_tags))).order_by("-same_tags" , "-published")[:2]
        comments = selected_post.comments.filter(active = True)
        return render(request , "blog/post_detail.html" , {
            "post": selected_post , "form":form , "similar_posts":similar_posts,
            "comments":comments})

    def post(self, request ,  slug , day,year,month):
        form = CommentForm(request.POST)
        selected_post = get_object_or_404(
            PostModel ,status= PostModel.Status.Published, slug = slug, published__day=day
            ,published__month = month , published__year=year
            )
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = selected_post
            comment.save()
            return redirect("blog:post_detail", slug=slug,day=day,year=year,month=month)
        return render(request , "blog/post_detail.html" , {
            "post" :selected_post , 
            "form" : form,
            "comments" : selected_post.comments.all()
        })
class SharePost(View):
    def get(self, request , id):
        post = get_object_or_404(PostModel , id =id , status= PostModel.Status.Published )
        form = EmailPostForm()
        sent = False
        return render(request , "blog/share.html" , {"post": post, "form": form , "sent":sent})
    def post(self, request , id):
        post = get_object_or_404(PostModel , id =id , status= PostModel.Status.Published )
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (f"{cd["name"]} : {cd["email"]}"
                       f"recommended for you: {post.title}")
            message= (f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}\'s comment: {cd['comments']}")
            send_mail(
                subject=subject,
                message=message,
                recipient_list=[cd["to"]]
            )
            sent= True
        else:
            sent =False
        return render(request , "blog/share.html" , {"post": post, "form": form , "sent":sent})
def just_get_it(request , id):
    selected_post = get_object_or_404(PostModel , id =id)
    return render(request, "blog/post_detail.html" , {"post": selected_post})


class PostSerach(View):
    def get(self, request):
        form = SearchForm()
        return render(request , "blog/search.html" , {"form":form})
    def post(self , request):
        form = SearchForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data["query"]
            #search_query = SearchQuery(query)
            #search_vector = SearchVector("title", weight="A") + SearchVector("content" , weight="B")
            #results = (PostModel.presented.annotate(search =search_vector , rank = SearchRank(search_vector , search_query)).filter(rank__gte = 0.3).order_by("-rank"))
            results = PostModel.presented.annotate(similarity = TrigramSimilarity("title" , query)).filter(similarity__gt=0.1).order_by("-similarity")
            return render(request , "blog/search.html" , {"form" : form ,"query":query , "results":results})
        return render(request , "blog/search.html" , {"form":form})

my_site/blog/templates/blog/all_posts.html
{% extends "base.html" %}
{% block page_title %}All posts{% endblock %}

{% block content %}
{% if tag %}
    <h1>Posts tagged with "{{tag.name}}"</h1>
{% else %}
    <h1>All posts</h1>
{% endif %}

{% for post in posts %}
<div class="card">
    <img src="{{post.image.url}}" class="post-image">

    <h2>
        <a href="{{post.get_absolute_url}}">
            {{post.title}}
        </a>
    </h2>

    <p class="meta">
        {{post.published}} · {{post.author}}
    </p>

    <p>
        {{post.content|truncatewords:30}}
    </p>

    <div class="tags">
        {% for tag in post.tags.all %}
            <span>
                <a href="{% url "blog:posts_by_tags" tag.slug %}">
                    {{tag.name}}{% if not forloop.last %}, {% endif %}
                </a>
            </span>
        {% endfor %}
    </div>
</div>
{% endfor %}

{% include "pagination.html" with page=page_obj %}
{% endblock %}

my_site/blog/templates/blog/home.html
{% extends "base.html" %}
{% load blog_tags %}
{% block page_title %}Deadlog{% endblock %}

{% block content %}
<h1>Latest Posts</h1>

{% for post in newposts %}
<div class="card">
    <img src="{{post.image.url}}" class="post-image">
    <h2>
        <a href="{{post.get_absolute_url}}">
            {{post.title}}
        </a>
    </h2>

    <p class="meta">
        {{post.published}} · {{post.author}}
    </p>

    <p>
        {{post.content|markdown|truncatewords_html:30}}
    </p>

    <div class="tags">
        {% for tag in post.tags.all %}
            <span>
                <a href="{% url "blog:posts_by_tags" tag.slug %}">
                    {{tag.name}}{% if not forloop.last %}, {% endif %}
                </a>
            </span>
        {% endfor %}
    </div>
</div>
{% endfor %}
{% endblock %}

my_site/blog/templates/blog/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

my_site/blog/templates/blog/post_detail.html
{% extends "base.html" %}
{% load blog_tags %}
{% block page_title %}{{post.title}}{% endblock %}

{% block content %}
<article class="card">
    <img src="{{post.image.url}}" class="post-image">

    <h1>{{post.title}}</h1>

    <p class="meta">
        {{post.published}} · {{post.author}}
    </p>

    <div class="tags">
        {% for tag in post.tags.all %}
            <span>
                <a href="{% url "blog:posts_by_tags" tag.slug %}">
                    {{tag.name}}{% if not forloop.last %}, {% endif %}
                </a></span>
        {% endfor %}
    </div>

    <div style="margin-top:2rem">
        {{post.content|markdown}}
    </div>

    <p>
        <a href="{% url "blog:share_post" post.id %}">Share this post</a>
    </p>
</article>

<!-- Similar posts -->
<div class="card">
    <h3>Similar posts</h3>
    {% for p in similar_posts %}
        <p>
            <a href="{{ p.get_absolute_url }}">{{p.title}}</a>
        </p>
    {% empty %}
        <p>No similar posts.</p>
    {% endfor %}
</div>
<!--latest posts-->
<h2> Latest posts:</h2>
{% show_latest_posts 3%}
<!--Most commented posts-->
<h2>Most commented posts</h2>
{% most_commented_posts as most_commented_posts %}
<ul>
    {% for post in most_commented_posts %}
        <li>
            <a href = "{{post.get_absolute_url}}">{{post.title}}</a>
        </li>
    {% endfor %}
</ul>
<!-- Comment form -->
<div class="card">
    <h3>Leave a comment</h3>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{field.label_tag}}<br>
                {{field}}
            </p>
        {% endfor %}
        <button class="btn" type="submit">Submit</button>
    </form>
</div>
<!-- Comments -->
<div class="card">
    <h3>Comments ({{comments.count}})</h3>

    {% for comment in comments %}
        <p class="meta">
            {{comment.name}} · {{comment.created}}
        </p>
        <p>{{comment.body|linebreaks}}</p>
        <hr>
    {% empty %}
        <p>No comments yet.</p>
    {% endfor %}
</div>


{% endblock %}

my_site/blog/templates/blog/search.html
{% extends "base.html" %}
{% load blog_tags %}
{% block page_title %}Search{% endblock page_title %}
{% block content %}
    {% if query %}
        <h3>
            {% with results.count as total_results%}
                Found {{total_results}} result{{total_results|pluralize}}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href = "{{post.get_absolute_url}}">{{post.title}}</a>
            </h4>
            {{post.content|markdown|truncatechars_html:14}}
        {%empty%}
            <p>No results for your query</p>
        {% endfor %}
    <a href= "{% url "blog:post_search" %}">Seacrh again</a>
    {% else %}
     <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <label>{{field.label}}</label>{{field}}
        {% endfor %}
        <button type="submit">Seacrh</button>
        </form>
    {% endif %}
{% endblock content %}

my_site/blog/templates/blog/share.html
{% extends "base.html" %}
{% block page_title %}Share{% endblock page_title %}

{% block content %}
    {% if sent %}
        <h2>Successfuly sent to {{form.cleaned_data.to}}</h2>
    {% else %}
        <h2>Share {{post.title}}</h2>
        <form method="POST">
            {% csrf_token %}
        {% for field in form %}
            <label>{{field.label}}</label>
            {{field}}
        {% endfor %}
        <button type="submit">Send</button>
        </form>
    {% endif %}
{% endblock content %}