bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include("account.urls")),
    path("social-auth/" , include("social_django.urls" , namespace="social")),
    path("images/" , include("images.urls" , namespace="images"))
] 

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path
from . import views

app_name = "images"
urlpatterns = [
    path("" , views.ImageList.as_view() , name="list"),
    path("create/" , views.CreateImage.as_view() , name="create"),
    path("detail/<int:id>/<slug:slug>/" , views.image_detail , name="detail"),
    path("like/" , views.ImageLike.as_view() , name="like")
]

bookmarks/images/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.text import slugify
# Create your models here.

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name="images_created", on_delete=models.CASCADE)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="liked_images", blank=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image =models.ImageField( upload_to="images/%Y/%m/%d/")
    url = models.URLField(max_length=2000)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=["-created_at"]),
        ] 
        ordering = ["-created_at"]

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args , **kwargs)
    def get_absolute_url(self):
        return reverse("images:detail", kwargs={"id": self.pk , "slug":self.slug})
    

bookmarks/images/forms.py
from django import forms 
import requests
from django.core.files.base import ContentFile
from PIL import Image as PILimage
from io import BytesIO
from django.utils.text import slugify
from .models import Image

class ImageForm(forms.ModelForm):   
    class Meta:
        model = Image
        fields = ["title" , "url" , "description"]
        widgets = {
            "url" : forms.HiddenInput(),
        }
    def clean_url(self):
        url = self.cleaned_data["url"]
        valid_extensions = ["jpeg" , "jpg" , "png"]
        extension = url.rsplit("." , 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError("This image format is not supported!")
        return url 
    def save(self, commit =True):
        image = super().save(commit = False)
        image_url = self.cleaned_data["url"]
        name = slugify(image.title)
        extension = image_url.rsplit("." , 1)[1].lower()
        image_name = f"{name}.{extension}"
        response = requests.get(image_url)
        response.raise_for_status()
        try:
            img = PILimage.open(BytesIO(response.content))
            img.verify()
        except (IOError, SyntaxError):
            forms.ValidationError("This is not a valid image.")
        image.image.save(
            image_name, ContentFile(response.content), save = False
        )
        if commit:
            image.save()
        return image

bookmarks/images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ImageForm
from django.contrib import messages
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import HttpResponse, Http404
from django.core.paginator import EmptyPage
from django.views.generic import View, ListView
from django.http import JsonResponse

# Create your views here.


class CreateImage(LoginRequiredMixin , View):
    def get(self, request):
        form = ImageForm(data = request.GET)
        return render(request , "images/image/create.html" , {"form":form , "section":"images"} )
    def post(self, request):
        form = ImageForm(data = request.POST) 
        if form.is_valid():
            cd = form.cleaned_data
            new_image= form.save(commit = False)
            new_image.user = request.user
            new_image.save()
            messages.success(request , "Image added successfuly")
            return redirect(new_image.get_absolute_url())
        return render(request , "images/image/create.html" , {"form":form,"section":"images"})
    


def image_detail(request , id, slug):
    image = get_object_or_404(Image , pk = id , slug =slug)
    return render(request , "images/image/detail.html" , {"section":"images" , "image": image})



class ImageLike(LoginRequiredMixin , View):
    def post(self, request):
        image_id = request.POST.get("id")
        action = request.POST.get("action")
        if image_id and action:
            try:
                image= Image.objects.get(pk = image_id)
                if action =="like":
                    image.users_like.add(request.user)
                else:
                    image.users_like.remove(request.user)
                return JsonResponse({"status": "ok"})
            except Image.DoesNotExist:
                pass
        return JsonResponse({"status": "error"})
            

class ImageList(LoginRequiredMixin, ListView):
    template_name = "images/image/list.html"
    model = Image
    context_object_name ="images"
    paginate_by = 8
    queryset = Image.objects.all()
    def get_context_data(self, **kwargs):
        context =  super().get_context_data(**kwargs)
        context["section"] = "images"
        return context
    def get_template_names(self):
        if self.request.GET.get("images_only"):
            return ["images/image/list_images.html"]
        return [self.template_name]
    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Http404:# task, when paginator tries an empty page, listview turns it into a Http404 error, customize the paginator subclass :)
            if request.GET.get("images_only"):
                return HttpResponse("", status=204)
            return HttpResponse("", status=204)

bookmarks/images/templates/images/image/create.html
{% extends "base.html" %}
{% block page_title %}Book mark an image{% endblock page_title %}

{% block content %}
    <h2>Bookmark an image</h2>
    <img src="{{request.GET.url}}"> 
    <form method = "POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Bookmark it!</button>
    </form>
{% endblock content %}

bookmarks/images/templates/images/image/detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block page_title %}{{image.title}}{% endblock page_title %}

{% block content %}
  <h1>{{ image.title }}</h1>
  <a href="{{image.image.url}}">
  <img src="{% thumbnail image.image 300x0 %}">
  </a>
  {% with total_likes=image.users_like.count users_like=image.users_like.all %}
    <div >
      <div>
        <span class="count">
          <span class="total">{{ total_likes }}</span> like{{ total_likes|pluralize }}
        </span>
        <a href="#" data-id ="{{image.id}}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button"> 
            {% if request.user in users_like %}
                Unlike
            {% else %}
                like
            {% endif %}
        </a>
      </div>
      {{ image.description|linebreaks }}
    </div>
    <div class="image-likes">
      {% for user in image.users_like.all %}
        <div>
          {% if user.profile.photo %}
            <img src="{{ user.profile.photo.url }}">
          {% endif %}
          <p>{{ user.first_name }}</p>
        </div>
      {% empty %}
        Nobody likes this image yet.
      {% endfor %}
    </div>
  {% endwith %}
{% endblock content %}

{% block domready %}
const url = '{% url "images:like" %}';

document.querySelector('a.like').addEventListener('click', function(e){
  e.preventDefault();

  var likeButton = this;

  var options = {
    method: 'POST',
    headers: {'X-CSRFToken': csrftoken},
    mode: 'same-origin'
  };

  var formData = new FormData();
  formData.append('id', likeButton.dataset.id);
  formData.append('action', likeButton.dataset.action);
  options['body'] = formData;

  fetch(url, options)
  .then(response => response.json())
  .then(data => {
    if (data['status'] === 'ok') {
      var previousAction = likeButton.dataset.action;
      var action = previousAction === 'like' ? 'unlike' : 'like';
      likeButton.dataset.action = action;
      likeButton.innerHTML = action;

      var likeCount = document.querySelector('span.count .total');
      var totalLikes = parseInt(likeCount.innerHTML);
      likeCount.innerHTML = previousAction === 'like'
        ? totalLikes + 1
        : totalLikes - 1;
    }
  });
});
{% endblock domready %}

bookmarks/images/templates/images/image/list.html
{% extends "base.html" %}
{% load thumbnail %}
{% block page_title %}Bookmarked images{% endblock page_title %}

{% block content %}
    <h1>Images bookmarked</h1>
    <div id="image-list">
    {% include "images/image/list_images.html" %}
    </div>
{% endblock content %}


{% block domready %}
  var page = 1;
  var emptyPage = false;
  var blockRequest = false;
  window.addEventListener('scroll', function(e) {
    var margin = document.body.clientHeight - window.innerHeight - 200;
    if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
      blockRequest = true;
      page += 1;
      fetch('?images_only=1&page=' + page)
      .then(response => response.text())
      .then(html => {
        if (html === '') {
          emptyPage = true;
        }
        else {
          var imageList = document.getElementById('image-list');
          imageList.insertAdjacentHTML('beforeEnd', html);
          blockRequest = false;
        }
      })
    }
  });
  // Launch scroll event
  const scrollEvent = new Event('scroll');
  window.dispatchEvent(scrollEvent);

{% endblock domready %}

bookmarks/images/templates/images/image/list_images.html
{% load thumbnail %}
<div>
        {% for image in images %}
            <div>
                <a href="{{image.get_absolute_url}}">
                    <img src="{% thumbnail image.image 300x300 crop="smart" %}">
                </a>
            </div>
            <div>
                <a href="{{image.get_absolute_url}}">{{image.title}}</a>
            </div>
        {% endfor %}
</div>