bookmarks/bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include("account.urls")),
    path("social-auth/" , include("social_django.urls" , namespace="social")),
    path("images/" , include("images.urls" , namespace="images"))
] 

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

bookmarks/images/urls.py
from django.urls import path
from . import views

app_name = "images"
urlpatterns = [
    path("" , views.ImageList.as_view() , name="list"),
    path("create/" , views.CreateImage.as_view() , name="create"),
    path("detail/<int:id>/<slug:slug>/" , views.image_detail , name="detail"),
    path("like/" , views.ImageLike.as_view() , name="like")
]

bookmarks/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang ="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel = "stylesheet" href="{% static "css/base.css" %}">
        {% block css_files %}{% endblock css_files %}
        <title>{% block page_title %}{% endblock page_title %}</title>
    </head>
    <body>
        <div id ="header">
            <span class = "logo">Bookmarks</span>
            {% if request.user.is_authenticated %}
                <ul>
                    <li {% if section == "dashboard" %}class="selected"{% endif %}>
                        <a href="{% url "dashboard" %}">My dashboard</a>
                    </li>
                    <li {% if section == "images" %}class="selected"{% endif %}>
                        <a href="{% url "images:list" %}">Images</a>
                    </li>
                    <li {% if section == "people" %}class="selected"{% endif %}>
                        <a href="{% url "users_list" %}">People</a>
                    </li>
                    
                </ul>
            {% endif %}
        <span class="user">
            {% if request.user.is_authenticated %}
                Hello {{ request.user.first_name|default:request.user.username }},
                <form action="{% url "logout" %}" method="post">
                <button type="submit">Logout</button>
                {% csrf_token %}
                </form>
            {% else %}
                <a href="{% url "login" %}">Log-in</a>
                <a href="{% url "register" %}">Register</a>
            {% endif %}
        </span>
        </div>
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{message|safe}}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
  <script src="//cdn.jsdelivr.net/npm/js-cookie@3.0.5/dist/js.cookie.min.js"></script>    
  <script>
    const csrftoken = Cookies.get('csrftoken'); 
    document.addEventListener('DOMContentLoaded', (event) =>{
        // DOM loaded
      {% block domready %}
      {% endblock %}
    })
  </script>
</html>