my_site/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name= "blog"
urlpatterns = [
    path("" , views.Home.as_view() , name = "home"),
    path("all_posts/" ,views.Posts.as_view() ,name = "all_posts"),
    path("tag/<slug:tag_slug>/" ,views.Posts.as_view() , name="posts_by_tags"),
    path("<int:year>/<int:month>/<int:day>/<slug:slug>" , views.PostDetail.as_view(), name ="post_detail"),
    path("<int:id>/" , views.just_get_it , name = "justgetit"),
    path("<int:id>/share-post/" , views.SharePost.as_view() , name = "share_post"),

    path("feed/" , LatestPostsFeed() , name="post_feed"),
    path("search/"  , views.PostSerach.as_view(), name= "post_search")
]

#task = learn how to use the custom model manager with Class based views, and make a "all blogs" page

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.conf import settings
from django.conf.urls.static import static
from blog.sitemaps import PostSitemap

sitemaps = {
    "posts": PostSitemap
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path("" , include("blog.urls" , namespace="blog")),
    path("sitemap.xml", sitemap, {"sitemaps":sitemaps} , name="django.contrib.sitemaps.views.sitemap"),
] + static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

my_site/templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>{% block page_title %}{% endblock page_title %}</title>
    {% block css_files %}{% endblock css_files %}
</head>
<body>
    <h2>i've written {%total_posts%} so far</h2>
    <a href = {% url "blog:all_posts" %}>All posts</a>
    <p>
        <a href = "{% url "blog:post_feed" %}">subscribe to my Rss feed</a>
    </p>
    {% block content %}{% endblock content %}
</body>
</html>